#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-jupyter_lsp
Version  : 2.2.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/01/f9/85c8361175208e279f63c3896db14b547d821c9cb8a52675e51a7bdb336f/jupyter-lsp-2.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/01/f9/85c8361175208e279f63c3896db14b547d821c9cb8a52675e51a7bdb336f/jupyter-lsp-2.2.0.tar.gz
Summary  : Multi-Language Server WebSocket proxy for Jupyter Notebook/Lab server
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-jupyter_lsp-license = %{version}-%{release}
Requires: pypi-jupyter_lsp-python = %{version}-%{release}
Requires: pypi-jupyter_lsp-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jupyter_server)
BuildRequires : pypi(pytest_runner)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# jupyter-lsp
Multi-[Language Server][language-server] WebSocket proxy for your Jupyter
`notebook` or `lab` server. For Python 3.6+.

%package license
Summary: license components for the pypi-jupyter_lsp package.
Group: Default

%description license
license components for the pypi-jupyter_lsp package.


%package python
Summary: python components for the pypi-jupyter_lsp package.
Group: Default
Requires: pypi-jupyter_lsp-python3 = %{version}-%{release}

%description python
python components for the pypi-jupyter_lsp package.


%package python3
Summary: python3 components for the pypi-jupyter_lsp package.
Group: Default
Requires: python3-core
Provides: pypi(jupyter_lsp)
Requires: pypi(jupyter_server)

%description python3
python3 components for the pypi-jupyter_lsp package.


%prep
%setup -q -n jupyter-lsp-2.2.0
cd %{_builddir}/jupyter-lsp-2.2.0
pushd ..
cp -a jupyter-lsp-2.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693509583
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jupyter_lsp
cp %{_builddir}/jupyter-lsp-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupyter_lsp/1eedac852d6365839b28a899f8da73121ae0aaab || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_notebook_config.d/jupyter-lsp-notebook.json
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/jupyter-lsp-jupyter-server.json
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jupyter_lsp/1eedac852d6365839b28a899f8da73121ae0aaab

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
